# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6cc4da76a26e6588439ec130cc9e1a71bf95731ebea5770849cf05c9af1def1597668525c6b2efe22247ee400bf33bff42875f3ce48d4bc36f5e45d876706fb

test:
  secret_key_base: 557f7d976b112c51f550ec14e837bc0ef88358cf62321bbcc16f1357a7ab72098e786b03b85726fe0f99f26b6b0d341f90b9d7dd7f9644739aafe45f12d69d33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
